# Generated by Django 6.0.3 on 2026-03-20 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Material')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Material')),
                ('tipo', models.CharField(choices=[('EM', 'Material Consumible (EM)'), ('EA', 'Activo Fijo (EA)'), ('EDC', 'Directo al Gasto (EDC)')], default='EM', max_length=3, verbose_name='Tipo de Material')),
                ('nro_parte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Parte')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='U.M.')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Actual')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': '1. Registro Maestro',
            },
        ),
        migrations.CreateModel(
            name='ReporteRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_reporte', models.CharField(blank=True, max_length=20, unique=True, verbose_name='No. Reporte (RP)')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Recepción')),
            ],
            options={
                'verbose_name': 'Reporte de Recepción',
                'verbose_name_plural': '2. Reportes Diarios (RP)',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_control_entrada', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nro. Control (EM/EA)')),
                ('nro_odc', models.CharField(max_length=50, verbose_name='Orden de Compra (ODC)')),
                ('nro_nota_entrega', models.CharField(max_length=50, verbose_name='Nota de Entrega')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cant. Solicitada (ODC)')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cant. Recibida Física')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='U.P. (USD)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.material', verbose_name='Material')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.reporterecepcion', verbose_name='Reporte (RP)')),
            ],
            options={
                'verbose_name': 'Recepción de Material',
                'verbose_name_plural': 'Control de Entradas (EM/EA)',
            },
        ),
        migrations.CreateModel(
            name='SalidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('nro_rim', models.CharField(max_length=50, verbose_name='No. RIM')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Despachada')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Despacho RIM',
                'verbose_name_plural': '3. Relación de Despachos (RIM)',
            },
        ),
    ]
