# Generated by Django 6.0.3 on 2026-04-10 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_guia', models.CharField(blank=True, max_length=50, unique=True, verbose_name='No. Guía (Automático)')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('hora', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora')),
                ('taladro_destino', models.CharField(choices=[('PRV-1', 'Taladro PRV-1'), ('PRV-3', 'Taladro PRV-3'), ('PRV-4', 'Taladro PRV-4'), ('BASE', 'Base Operativa / Otro')], max_length=20, verbose_name='Destino')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(default='MORICHAL', max_length=100, verbose_name='Ciudad')),
                ('conductor', models.CharField(max_length=100, verbose_name='Conductor')),
                ('ci_conductor', models.CharField(max_length=20, verbose_name='C.I.')),
                ('vehiculo', models.CharField(max_length=50, verbose_name='Vehículo (Ej. CARGO)')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('placa', models.CharField(max_length=20, verbose_name='Placa')),
                ('marca_modelo', models.CharField(max_length=100, verbose_name='Marca / Modelo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('nombre_entregado', models.CharField(default='Almacén El Tigre', max_length=100, verbose_name='Entregado por')),
            ],
            options={
                'verbose_name': 'Guía de Traslado',
                'verbose_name_plural': '4. Guías de Traslado',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Material')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Material')),
                ('tipo', models.CharField(choices=[('MATERIAL', 'MATERIAL'), ('ACTIVOS', 'ACTIVOS'), ('DIRECTO AL GASTO', 'DIRECTO AL GASTO')], default='MATERIAL', max_length=20, verbose_name='Tipo de Material')),
                ('cargo', models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('OPERACIONES', 'Operaciones'), ('TRANSPORTE', 'Transporte'), ('OTRO', 'Otro')], default='OPERACIONES', max_length=50, verbose_name='Cargo / Uso')),
                ('nro_parte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Parte')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='U.M.')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Actual')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': '1. Registro Maestro',
            },
        ),
        migrations.CreateModel(
            name='ReporteRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_reporte', models.CharField(blank=True, max_length=20, unique=True, verbose_name='No. Reporte (RP)')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Recepción')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción General')),
            ],
            options={
                'verbose_name': 'Reporte de Recepción',
                'verbose_name_plural': '2. Reportes Diarios (RP)',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Recepción')),
                ('nro_control_entrada', models.CharField(blank=True, max_length=20, verbose_name='Nro. Control (EM/EA)')),
                ('nro_odc', models.CharField(max_length=50, verbose_name='Orden de Compra (ODC)')),
                ('nro_nota_entrega', models.CharField(max_length=50, verbose_name='Nota de Entrega')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cant. Solicitada (ODC)')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cant. Recibida Física')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='U.P. (USD)')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.material', verbose_name='Material')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.reporterecepcion', verbose_name='Reporte (RP)')),
            ],
            options={
                'verbose_name': 'Recepción de Material',
                'verbose_name_plural': 'Control de Entradas',
            },
        ),
        migrations.CreateModel(
            name='SalidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Despacho')),
                ('nro_rim', models.CharField(max_length=50, verbose_name='No. RIM (Requisición)')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Despachada')),
                ('centro_costo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro de Costo')),
                ('cuenta_contable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuenta Contable')),
                ('partida_presupuestaria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Partida Presupuestaria')),
                ('guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.guiatraslado', verbose_name='¿Va en alguna Guía?')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.material', verbose_name='Material a Despachar')),
            ],
            options={
                'verbose_name': 'Despacho RIM',
                'verbose_name_plural': '3. Relación de Despachos (RIM)',
            },
        ),
    ]
