# Generated by Django 6.0.3 on 2026-04-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cargo',
            field=models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('OPERACIONES', 'Operaciones'), ('TRANSPORTE', 'Transporte'), ('OTRO', 'Otro')], default='OPERACIONES', max_length=50, verbose_name='Cargo / Uso'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='centro_costo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro de Costo'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='cuenta_contable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuenta Contable'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='partida_presupuestaria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Partida Presupuestaria'),
        ),
    ]
