# Generated by Django 5.2.13 on 2026-04-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcion',
            name='eta',
            field=models.DateField(blank=True, null=True, verbose_name='ETA'),
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='fecha_firma_odc',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Firma ODC'),
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='moneda',
            field=models.CharField(default='USD', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guiatraslado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reporterecepcion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salidamaterialdetalle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
