# Generated by Django 6.0.3 on 2026-03-25 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_guia', models.CharField(blank=True, max_length=50, unique=True, verbose_name='No. Guía (Automático)')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('hora', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora')),
                ('taladro_destino', models.CharField(choices=[('PRV-1', 'Taladro PRV-1'), ('PRV-3', 'Taladro PRV-3'), ('PRV-4', 'Taladro PRV-4'), ('BASE', 'Base Operativa / Otro')], max_length=20, verbose_name='Destino')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(default='MORICHAL', max_length=100, verbose_name='Ciudad')),
                ('conductor', models.CharField(max_length=100, verbose_name='Conductor')),
                ('ci_conductor', models.CharField(max_length=20, verbose_name='C.I.')),
                ('vehiculo', models.CharField(max_length=50, verbose_name='Vehículo (Ej. CARGO)')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('placa', models.CharField(max_length=20, verbose_name='Placa')),
                ('marca_modelo', models.CharField(max_length=100, verbose_name='Marca / Modelo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('nombre_entregado', models.CharField(default='Almacén El Tigre', max_length=100, verbose_name='Entregado por')),
            ],
            options={
                'verbose_name': 'Guía de Traslado',
                'verbose_name_plural': '4. Guías de Traslado',
            },
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='fecha_despacho',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Despacho'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.material', verbose_name='Material a Despachar'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='nro_rim',
            field=models.CharField(max_length=50, verbose_name='No. RIM (Requisición)'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.guiatraslado', verbose_name='¿Va en alguna Guía?'),
        ),
    ]
