# Generated by Django 6.0.3 on 2026-04-06 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_guiatraslado_alter_salidamaterial_fecha_despacho_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallerecepcion',
            options={'verbose_name': 'Recepción de Material', 'verbose_name_plural': 'Control de Entradas'},
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='fecha_recepcion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Recepción'),
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='reporterecepcion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción General'),
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='nro_control_entrada',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nro. Control (EM/EA)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('MATERIAL', 'MATERIAL'), ('ACTIVOS', 'ACTIVOS'), ('DIRECTO AL GASTO', 'DIRECTO AL GASTO')], default='MATERIAL', max_length=20, verbose_name='Tipo de Material'),
        ),
    ]
