# Generated by Django 5.2.13 on 2026-04-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_detallerecepcion_id_alter_guiatraslado_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcion',
            name='descripcion_entrada',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción (según ODC)'),
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.material', verbose_name='Material (Cód. Catálogo)'),
        ),
    ]
