# Generated by Django 5.2.13 on 2026-04-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_detallerecepcion_descripcion_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año Fiscal (Ej. 2026)')),
                ('departamento', models.CharField(max_length=100, verbose_name='Dpto / Centro de Costo')),
                ('cuenta_contable', models.CharField(max_length=100, verbose_name='Cuenta Contable')),
                ('descripcion_cuenta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Cuenta')),
                ('partida', models.CharField(max_length=200, verbose_name='Partida Presupuestaria')),
            ],
            options={
                'verbose_name': 'Partida Presupuestaria',
                'verbose_name_plural': 'Config. Finanzas (Partidas)',
            },
        ),
    ]
