# Generated by Django 6.0.3 on 2026-04-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_centrocosto_alter_detallerecepcion_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrocosto',
            options={'ordering': ['nombre'], 'verbose_name': 'Centro de Costo', 'verbose_name_plural': 'Config. Centros de Costo'},
        ),
        migrations.RemoveField(
            model_name='centrocosto',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Centro de Costo'),
        ),
    ]
