# Generated by Django 6.0.3 on 2026-04-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_centrocosto_options_remove_centrocosto_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidamaterial',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento Solicitante'),
        ),
    ]
