# Generated by Django 6.0.3 on 2026-04-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_salidamaterial_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallerecepcion',
            options={'verbose_name': 'Entradas del Almacen', 'verbose_name_plural': 'Control de Entradas'},
        ),
        migrations.AddField(
            model_name='reporterecepcion',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10, verbose_name='Estado del Reporte'),
        ),
    ]
