# Generated by Django 6.0.3 on 2026-04-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_detallerecepcion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporterecepcion',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10, verbose_name='Estado'),
        ),
    ]
