# Generated by Django 6.0.3 on 2026-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_reporterecepcion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcion',
            name='volumen_carpeta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Volumen Carpeta'),
        ),
    ]
