# Generated by Django 6.0.3 on 2026-04-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_detallerecepcion_volumen_carpeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcion',
            name='es_saldo_inicial',
            field=models.BooleanField(default=False, verbose_name='¿Es Saldo Inicial?'),
        ),
    ]
