# Generated by Django 5.2.13 on 2026-04-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_centrocosto_id_alter_detallerecepcion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiatraslado',
            name='taladro_destino',
            field=models.CharField(choices=[('PRV-1', 'PRV-1'), ('PRV-2', 'PRV-2'), ('PRV-3', 'PRV-3'), ('PRV-4', 'PRV-4'), ('PRV-5', 'PRV-5'), ('PRV-6', 'PRV-6'), ('PRV-7', 'PRV-7'), ('TERCEROS', 'TERCEROS')], max_length=20, verbose_name='Destino'),
        ),
    ]
