# Generated by Django 5.2.13 on 2026-04-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_guiatraslado_taladro_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiatraslado',
            name='nombre_aprobador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aprobado en Almacén por'),
        ),
        migrations.AlterField(
            model_name='guiatraslado',
            name='taladro_destino',
            field=models.CharField(choices=[('PRV-1', 'PRV-1'), ('PRV-2', 'PRV-2'), ('PRV-3', 'PRV-3'), ('PRV-4', 'PRV-4'), ('PRV-5', 'PRV-5'), ('PRV-6', 'PRV-6'), ('PRV-7', 'PRV-7'), ('ALM', 'TERCEROS')], max_length=20, verbose_name='Destino'),
        ),
    ]
