# Generated by Django 6.0.3 on 2026-04-30 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_guiatraslado_nombre_aprobador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocosto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guiatraslado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guiatraslado',
            name='taladro_destino',
            field=models.CharField(choices=[('PRV-1', 'PRV-1'), ('PRV-2', 'PRV-2'), ('PRV-3', 'PRV-3'), ('PRV-4', 'PRV-4'), ('PRV-5', 'PRV-5'), ('PRV-6', 'PRV-6'), ('PRV-7', 'PRV-7'), ('ALM', 'ALM'), ('TERCEROS', 'TERCEROS')], max_length=20, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='presupuestoanual',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reporterecepcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='nro_rim',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_rim_format', message='El formato del Nro. RIM es inválido. Debe seguir el patrón DPT-000-AÑO (Ej. OPE-001-2026).', regex='^[A-Z]{3,4}-\\d{3}-\\d{4}$')], verbose_name='No. RIM (Requisición)'),
        ),
        migrations.AlterField(
            model_name='salidamaterialdetalle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
