# Generated by Django 5.2.13 on 2026-04-30 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_alter_centrocosto_id_alter_detallerecepcion_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='guiatraslado',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Generado por'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Despachado por'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.material', verbose_name='Material a Despachar'),
        ),
    ]
