# Generated by Django 5.2.13 on 2026-04-30 16:49

import datetime
import django.core.validators
import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_pilar1_integridad_referencial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallerecepcion',
            options={'ordering': ['-fecha_recepcion', '-id'], 'verbose_name': 'Entradas del Almacen', 'verbose_name_plural': 'Control de Entradas'},
        ),
        migrations.AlterModelOptions(
            name='guiatraslado',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Guía de Traslado', 'verbose_name_plural': '4. Guías de Traslado'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['codigo'], 'verbose_name': 'Material', 'verbose_name_plural': '1. Registro Maestro'},
        ),
        migrations.AlterModelOptions(
            name='reporterecepcion',
            options={'ordering': ['-fecha_recepcion', '-id'], 'verbose_name': 'Reporte de Recepción', 'verbose_name_plural': '2. Reportes Diarios (RP)'},
        ),
        migrations.AlterModelOptions(
            name='salidamaterial',
            options={'ordering': ['-fecha_despacho', '-id'], 'verbose_name': 'Despacho RIM', 'verbose_name_plural': '3. Relación de Despachos (RIM)'},
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='guiatraslado',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='guiatraslado',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='material',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='material',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='reporterecepcion',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='reporterecepcion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Modificación'),
        ),
        migrations.RenameField(model_name='salidamaterial', old_name='centro_costo', new_name='centro_costo_texto'),
        migrations.AddField(
            model_name='salidamaterial',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='salidamaterialdetalle',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='salidamaterialdetalle',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='fecha_recepcion',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Fecha de Recepción'),
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='inventario.material', verbose_name='Material (Cód. Catálogo)'),
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD'), ('BS', 'Bolívares'), ('EUR', 'EUR')], default='USD', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='nro_control_entrada',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Nro. Control (EM/EA)'),
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='nro_odc',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Orden de Compra (ODC)'),
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='inventario.reporterecepcion', verbose_name='Reporte (RP)'),
        ),
        migrations.AlterField(
            model_name='guiatraslado',
            name='fecha',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='guiatraslado',
            name='hora',
            field=models.TimeField(default=inventario.models.hora_local_actual, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='guiatraslado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guiatraslado',
            name='taladro_destino',
            field=models.CharField(choices=[('PRV-1', 'PRV-1'), ('PRV-2', 'PRV-2'), ('PRV-3', 'PRV-3'), ('PRV-4', 'PRV-4'), ('PRV-5', 'PRV-5'), ('PRV-6', 'PRV-6'), ('PRV-7', 'PRV-7'), ('ALM', 'ALM'), ('TERCEROS', 'TERCEROS')], db_index=True, max_length=20, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='presupuestoanual',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reporterecepcion',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], db_index=True, default='ABIERTO', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reporterecepcion',
            name='fecha_recepcion',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Fecha de Recepción'),
        ),
        migrations.AlterField(
            model_name='reporterecepcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(model_name='salidamaterial', name='centro_costo', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='inventario.centrocosto', verbose_name='Centro de Costo')),
        migrations.AlterField(
            model_name='salidamaterial',
            name='departamento',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Departamento Solicitante'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='fecha_despacho',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Fecha de Despacho'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='inventario.guiatraslado', verbose_name='¿Va en alguna Guía?'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='inventario.material', verbose_name='Material a Despachar'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='nro_rim',
            field=models.CharField(db_index=True, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_rim_format', message='El formato del Nro. RIM es inválido. Debe seguir el patrón DPT-000-AÑO (Ej. OPE-001-2026).', regex='^[A-Z]{3,4}-\\d{3}-\\d{4}$')], verbose_name='No. RIM (Requisición)'),
        ),
        migrations.AlterField(
            model_name='salidamaterialdetalle',
            name='detalle_recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_salida', to='inventario.detallerecepcion', verbose_name='ODC Origen'),
        ),
        migrations.AlterField(
            model_name='salidamaterialdetalle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='presupuestoanual',
            index=models.Index(fields=['anio', 'departamento'], name='idx_presupuesto_anio_depto'),
        ),
    ]
