# Generated by Django 5.2.13 on 2026-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_pilar_2_3_4_5_correcciones_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoanual',
            name='rubro_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro 1'),
        ),
        migrations.AddField(
            model_name='presupuestoanual',
            name='rubro_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro 2'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='descripcion_cuenta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción de la Cuenta'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='nro_sm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. SM (Solicitud)'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='rubro_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro 1'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='rubro_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro 2'),
        ),
        migrations.AlterField(
            model_name='guiatraslado',
            name='taladro_destino',
            field=models.CharField(choices=[('PRV-1', 'PRV-1'), ('PRV-2', 'PRV-2'), ('PRV-3', 'PRV-3'), ('PRV-4', 'PRV-4'), ('PRV-5', 'PRV-5'), ('PRV-6', 'PRV-6'), ('PRV-7', 'PRV-7'), ('TERCEROS', 'ALM')], db_index=True, max_length=20, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='centro_costo_texto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro de Costo (Texto)'),
        ),
    ]
