# Generated by Django 5.2.13 on 2026-05-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_presupuestoanual_rubro_1_presupuestoanual_rubro_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidamaterial',
            name='numero_salida_correlativo',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Nro. Correlativo'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='tipo_salida',
            field=models.CharField(choices=[('SM', 'Salida de Materiales'), ('SA', 'Salida de Activos'), ('SDG', 'Salida Directo al Gasto')], default='SM', max_length=5, verbose_name='Tipo de Salida'),
        ),
    ]
