# Generated by Django 5.2.13 on 2026-05-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_salidamaterial_numero_salida_correlativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_activo', models.CharField(max_length=50, unique=True, verbose_name='Código de Activo')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Activo')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro. de Serie')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Cantidad')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación Física')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': '1B. Inventario de Activos Fijos',
                'ordering': ['codigo_activo'],
            },
        ),
    ]
