# Generated by Django 5.2.13 on 2026-05-13 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcion',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='inventario.activo', verbose_name='Activo (Cód. Catálogo)'),
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='tipo_ingreso',
            field=models.CharField(choices=[('Material', 'Material'), ('Activo', 'Activo')], default='Material', max_length=10, verbose_name='Tipo de Ingreso'),
        ),
        migrations.AlterModelTable(
            name='activo',
            table='inventario_activo',
        ),
    ]
