# Generated by Django 5.2.13 on 2026-05-13 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_rename_serie_activo_serial_detallerecepcion_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidamaterial',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='inventario.activo', verbose_name='Activo a Despachar'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='inventario.material', verbose_name='Material a Despachar'),
        ),
    ]
