# Generated by Django 5.2.13 on 2026-05-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_remove_activo_serie_activo_cargo_ac_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activo',
            old_name='serie',
            new_name='serial',
        ),
        migrations.AddField(
            model_name='activo',
            name='cargo_ac',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo / Departamento'),
        ),
        migrations.AddField(
            model_name='activo',
            name='nro_parte_ac',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro. de Parte'),
        ),
        migrations.AddField(
            model_name='activo',
            name='unidad_medida_ac',
            field=models.CharField(default='UNID', max_length=50, verbose_name='Unidad de Medida'),
        ),
    ]
