# Generated by Django 5.2.13 on 2026-05-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_rename_serie_activo_serial_activo_cargo_ac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiatraslado',
            name='marca_modelo',
        ),
        migrations.AddField(
            model_name='guiatraslado',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='guiatraslado',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
    ]
