# Generated by Django 5.2.13 on 2026-05-15 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_remove_guiatraslado_marca_modelo_guiatraslado_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dg', models.CharField(max_length=50, unique=True, verbose_name='Código DG')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('unidad_medida_dg', models.CharField(max_length=50, verbose_name='U.M.')),
                ('nro_parte_dg', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro. Parte')),
                ('cargo_dg', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Gasto Directo',
                'verbose_name_plural': '1C. Registro de Gasto Directo',
                'db_table': 'inventario_DG',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='tipo_ingreso',
            field=models.CharField(choices=[('Material', 'Material'), ('Activo', 'Activo')], default='Material', max_length=30, verbose_name='Tipo de Ingreso'),
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='gasto_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='inventario.gastodirecto', verbose_name='Gasto Directo'),
        ),
    ]
