# Generated by Django 5.2.13 on 2026-05-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_gastodirecto_alter_detallerecepcion_tipo_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastodirecto',
            options={'managed': False, 'verbose_name': 'Artículo Directo al Gasto', 'verbose_name_plural': '1C. Catálogo de Gasto Directo (EDG)'},
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='gasto_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='inventario.gastodirecto', verbose_name='Gasto Directo (Cód. DG)'),
        ),
        migrations.AlterField(
            model_name='detallerecepcion',
            name='gasto_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='inventario.gastodirecto', verbose_name='Gasto Directo (Cód. DG)'),
        ),
    ]
