# Generated by Django 5.2.13 on 2026-05-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_alter_gastodirecto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('agregado_el', models.DateTimeField(auto_now_add=True, verbose_name='Agregado el')),
            ],
            options={
                'verbose_name': 'Correo Autorizado',
                'verbose_name_plural': 'Lista Blanca de Correos',
            },
        ),
    ]
