# Generated by Django 5.2.13 on 2026-05-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_registroactividad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorreoAutorizado',
        ),
    ]
