# Generated by Django 5.2.13 on 2026-05-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_delete_correoautorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='Código QR'),
        ),
        migrations.AddField(
            model_name='material',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='Código QR'),
        ),
    ]
